[launcher]
author=Tony Vincent
description=Oura Ring health and wellness dashboards powered by Splunk Dashboard Studio. Source & docs: https://github.com/narwhaldc/oura-health-splunk
version=1.8.34
build=20260716f

[package]
id=oura_health

[ui]
is_visible=1
label=Oura Health

[id]
group=
name=oura_health
version=1.8.34
